version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - get-smart/oberbaum
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    reviewers:
      - get-smart/oberbaum
