name: Test

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request_target:
    types: [labeled]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - 'head'

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@v1.147.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
