name: Test

on:
  push:
    branches-ignore:
      - "dependabot/**"
    pull_request_target:
      types: [labeled]

jobs:
  test:
    name: Test
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') || github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby:
          # todo: remove EOL ruby versions once gemspec is updated
          - '1.9.3'
          - '2.0'
          - '2.1'
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - head
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.5.0
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@v1.146.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake spec
